version: 2
updates:
    -   package-ecosystem: gradle
        directory: "/"
        schedule:
            interval: daily
            time: "08:50"
        open-pull-requests-limit: 20
        target-branch: develop
